import { Label } from "@/components/ui/label";
import { useDashboardStore } from "@/store/dashboard";
import { useSidebarStore } from "@/store/sidebar";
import PageButtons from "@/components/dashboard/pageButton";
import { cn } from "@/lib/utils";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { COMMAND_MODEL_OPTIONS } from "@/constants/dashboard";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { InfoIcon } from "lucide-react";

export function DashboardHeader() {
  const { currentFolder } = useSidebarStore();
  const { commandModel, setCommandModel } = useDashboardStore();

  return (
    <div className="flex flex-col justify-center py-1 px-2 sticky h-10 top-10 z-5">
      <div className="flex flex-row items-center justify-between">
        <div className="flex flex-row items-center gap-2">
          <ShowTitle />
          <Select
            value={commandModel}
            onValueChange={(v) =>
              setCommandModel(v as (typeof COMMAND_MODEL_OPTIONS)[number])
            }
          >
            <SelectTrigger className="w-[100px]">
              <SelectValue placeholder="Model" />
            </SelectTrigger>
            <SelectContent>
              {COMMAND_MODEL_OPTIONS.map((model) => (
                <SelectItem key={model} value={model}>
                  {model}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Dialog>
            <DialogTrigger>
              <InfoIcon className="size-5 text-primary" />
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Command Usage</DialogTitle>
                <DialogDescription asChild>
                  <CommandUsage />
                </DialogDescription>
              </DialogHeader>
            </DialogContent>
          </Dialog>
        </div>
        {currentFolder && <PageButtons />}
      </div>
    </div>
  );
}

function CommandUsage() {
  return (
    <div className="space-y-4">
      <div className="space-y-2">
        <p className="text-sm">
          // Content enclosed with
          <code className="bg-muted px-1 rounded">&quot;-&gt;&quot;</code> and
          <code className="bg-muted px-1 rounded">&quot;&lt;-&quot;</code> is
          recognized as a command. Use the following format to get a response:
        </p>
        <p className="text-xs text-muted-foreground bg-muted p-2 rounded font-mono">
          -&gt; query &lt;-
        </p>
      </div>
      <div className="space-y-2">
        <p className="text-sm">
          The response will be generated by following format:
        </p>
        <p className="text-xs text-muted-foreground bg-muted p-2 rounded font-mono">
          -&gt;
          <br />
          query
          <br />
          --
          <br />
          response
          <br />
          &lt;-
        </p>
      </div>
      <div className="space-y-2">
        <p className="text-sm">
          // Content enclosed with
          <code className="bg-muted px-1 rounded">&quot;&gt;&gt;&quot;</code>
          and
          <code className="bg-muted px-1 rounded">&quot;&lt;&lt;&quot;</code>
          can be deleted. Use the following format to delete:
        </p>
        <p className="text-xs text-muted-foreground bg-muted p-2 rounded font-mono">
          &gt;&gt; query &lt;&lt;
        </p>
      </div>
      <div className="space-y-2">
        <p className="text-sm">
          // Choose the model you want to use for the command.
        </p>
      </div>
    </div>
  );
}

function ShowTitle() {
  const { currentFile } = useDashboardStore();
  const { currentFolder } = useSidebarStore();

  return (
    <div className="flex flex-row items-center max-w-full truncate overflow-x-auto scrollbar-hide">
      <span className="text-xs text-muted-foreground px-1">
        {currentFolder?.name} -&gt; {currentFile?.page} :
      </span>
      <Label
        className={cn(
          currentFile?.title ? "text-primary" : "text-muted-foreground",
        )}
      >
        {currentFile?.title ? currentFile.title : "None"}
      </Label>
    </div>
  );
}
